Get thor mem fix 0.14.1
OdinProAgrica/hpycc pull request #116
Opened 2018-11-29 13:18 UTC by mansfieldbitter

Code changes as discussed, we've reviewed at my machine so feel free to wave through ;)

All tests green

2018-12-07 10:01 UTC, cqkh42 requested changes

2018-12-08 04:19 UTC, datamacgyver commented on hpycc/save.py
> +def save_outputs(connection, script, directory=".", overwrite=True,
Hadn't disabled everything. Done now.

2018-12-08 04:20 UTC, datamacgyver commented on hpycc/connection.py
> +lock = threading.Lock()
Not any more. Removed.

2018-12-08 04:58 UTC, datamacgyver commented on README.rst
> +Tests and docker contianer functions require docker to spin up HPCC environments.
done

2018-12-08 04:59 UTC, datamacgyver commented
Changes pushed. Feel free to merge when ready.

2018-12-12 14:46 UTC, merged